"""Reproduction protects frozen observations and their deterministic serialization."""
import json
from pathlib import Path
import re
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]


def normalized_bytes(content):
    # Check the scope before replacing timestamp values in the original bytes:
    # parsing and re-serializing here would conceal writer or key-order drift.
    def walk(value, parent=None):
        if isinstance(value, dict):
            for key, child in value.items():
                if key == 'submitted_at':
                    if parent != 'compact' or not isinstance(child, str):
                        raise AssertionError('Unexpected submitted_at outside compact')
                walk(child, key)
        elif isinstance(value, list):
            for child in value:
                walk(child, parent)
    walk(json.loads(content))
    return re.sub(rb'("submitted_at"\s*:\s*)"(?:[^"\\]|\\.)*"',
                  rb'\1"<timestamp>"', content)


class ModelDiscoveryReproductionTests(unittest.TestCase):
    def test_every_lane_reproduces_committed_bytes(self):
        schema = json.loads((ROOT / 'docs/discovery/handoff-schema.json').read_text())
        with tempfile.TemporaryDirectory() as directory:
            for lane in schema['lanes']['models']:
                with self.subTest(lane=lane):
                    result = subprocess.run(
                        ['node', 'scripts/model_discovery.mjs', lane, directory],
                        cwd=ROOT, capture_output=True, text=True, timeout=180)
                    self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                    filename = f'{lane}-runtime.json'
                    generated = normalized_bytes((Path(directory) / filename).read_bytes())
                    committed = normalized_bytes((ROOT / 'docs/discovery' / filename).read_bytes())
                    self.assertTrue(generated == committed,
                                    f'{lane}: generated bytes differ after compact.submitted_at normalization')


if __name__ == '__main__':
    unittest.main()
