"""Deployable packages for completed releases and one-step publish.

Run: python -m catalog.deploy package --store STORE --release RELEASE_ID [--output DIR]
     python -m catalog.deploy ship --database DRAFT [--backup-dir DIR]

A package is a container build folder: a Dockerfile, a start script and a store
holding only one verified release. The release runs on its own pinned code, so
publishing a different release means deploying its package; rollback deploys the
previous package. Uploading to the host is a separate step.
"""
import argparse
from contextlib import closing
import os
from pathlib import Path
import shutil
import tempfile

from catalog import authoring
from catalog.consumers import encode
from catalog.releases import ReleaseStore, database_hash

CHANNEL = 'production'

DOCKERFILE = """\
# Generated by catalog.deploy for release {release}. Do not edit; package again.
FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /srv
COPY store /srv/store
COPY start.sh /srv/start.sh
RUN chmod 0555 /srv/start.sh
EXPOSE 8080
CMD ["/srv/start.sh"]
"""

START = """\
#!/bin/sh
# Generated by catalog.deploy for release {release}.
# Required: CATALOG_ORIGIN (space-separated public origins) and CATALOG_BUILD_TOKEN_KEY.
# Optional: PORT (default 8080), CATALOG_DEALER_SUBMISSIONS=1 for live dealer delivery.
set -eu
: "${{CATALOG_ORIGIN:?Set CATALOG_ORIGIN to the public address, e.g. https://build.example.com}}"
set -- --store /srv/store --release {release} --host 0.0.0.0 --port "${{PORT:-8080}}"
for origin in $CATALOG_ORIGIN; do set -- "$@" --origin "$origin"; done
if [ "${{CATALOG_DEALER_SUBMISSIONS:-}}" = 1 ]; then set -- "$@" --enable-dealer-submissions; fi
exec env PYTHONPATH=/srv/store/completed/{release}/runtime python -P -m catalog.consumer_server "$@"
"""


def package(store, release, destination):
    """Write a verified deploy folder once; an existing one is verified, never replaced."""
    destination = Path(destination)
    if destination.exists():
        store._verify_path(destination / 'store/completed' / release, release)
        for name, text in (('Dockerfile', DOCKERFILE), ('start.sh', START)):
            if (destination / name).read_text() != text.format(release=release):
                raise ValueError(f'Existing package {name} differs; move it aside and package again')
        return destination
    store.verify(release)
    destination.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix='.package-', dir=destination.parent))
    try:
        target = stage / 'store/completed' / release
        shutil.copytree(store.completed / release, target)
        store._verify_path(target, release)
        (stage / 'Dockerfile').write_text(DOCKERFILE.format(release=release))
        (stage / 'start.sh').write_text(START.format(release=release))
        os.chmod(stage / 'start.sh', 0o755)
        os.rename(stage, destination)
    finally:
        if stage.exists():
            shutil.rmtree(stage)
    return destination


def publish(store, release, expected_version, deploy_root):
    """Package the release, then move the production pointer (compare-and-swap).

    Packaging first means production never names a release without a package.
    """
    folder = package(store, release, Path(deploy_root) / release)
    return dict(pointer=store.publish(release, expected_version, CHANNEL), package=str(folder))


def ship(database, backup_dir=None):
    """Accepted draft to published, packaged release in one step."""
    from catalog.authoring_server import build_release
    database = Path(database)
    with closing(authoring.open_workspace(database)) as db:
        digest = database_hash(db)
    # Read the pointer before the long build so a publish made meanwhile is
    # reported as stale rather than silently replaced.
    expected = ReleaseStore(database.resolve().parent / 'releases').pointer(CHANNEL)['version']
    built = build_release(database, digest, backup_dir)
    store = ReleaseStore(built['store'])
    published = publish(store, built['release_id'], expected, database.resolve().parent / 'deploy')
    return dict(built, **published)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest='command', required=True)
    pack = commands.add_parser('package', help='Write the deploy folder for one completed release')
    pack.add_argument('--store', type=Path, required=True)
    pack.add_argument('--release', required=True)
    pack.add_argument('--output', type=Path, help='Default: deploy/RELEASE_ID next to the store')
    go = commands.add_parser('ship', help='Release, publish and package an accepted draft')
    go.add_argument('--database', type=Path, required=True)
    go.add_argument('--backup-dir', type=Path)
    args = parser.parse_args()
    if args.command == 'package':
        store = ReleaseStore(args.store)
        print(package(store, args.release, args.output or store.root.parent / 'deploy' / args.release))
    else:
        print(encode(ship(args.database, args.backup_dir)))


if __name__ == '__main__':
    main()
