'use strict';
const $=id=>document.getElementById(id),node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;},pretty=s=>s.replaceAll('_',' ');
let data=null,pending=null,busy=false;
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function showValue(parent,value,path=''){if(value&&typeof value==='object'){for(const [k,v] of Object.entries(value))showValue(parent,v,path+pretty(k)+' / ');}else parent.append(node('p',path.slice(0,-3)+': '+(value??'None')));}
function showHistory(parent,history){parent.replaceChildren();for(const item of history){const h=item.event,d=node('details','');d.append(node('summary',`Edit ${h.edit_version} · ${pretty(item.table.replace('authoring_','').replace('_change',''))} · ${h.reason}`),node('p',h.saved_at));if(h.operations_json){for(const op of JSON.parse(h.operations_json)){const part=node('details','');part.append(node('summary',pretty(op.table)),node('h3','Before'));showValue(part,op.before);part.append(node('h3','After'));showValue(part,op.after);d.append(part);}const evidence=node('details','');evidence.append(node('summary','Source evidence'));showValue(evidence,JSON.parse(h.evidence_json));d.append(evidence);}else{d.append(node('h3','Before'));showValue(d,JSON.parse(h.before_json));d.append(node('h3','After'));showValue(d,JSON.parse(h.after_json));}parent.append(d);}if(!history.length)parent.append(node('p','No saved edits to accept.'));}
async function load(){data=await api('/api/acceptance');showHistory($('history'),data.history);$('accepted').replaceChildren(...data.acceptances.map(a=>node('p',`${a.accepted_at} · ${a.reviewer} · ${a.reason}`)));$('intake').replaceChildren();for(const item of data.intake){const d=node('details','');d.dataset.intake=item.intake_id;const payload=JSON.parse(item.payload_json);d.append(node('summary',`${pretty(item.disposition)} · ${payload.assertion}`));showValue(d,payload);if(['pending','deferred'].includes(item.disposition)){const include=node('label','Include in this acceptance');const box=node('input','');box.type='checkbox';box.className='include';include.append(box);const resolution=node('label','Evidence and ambiguity resolution'),area=node('textarea','');area.className='resolution';resolution.append(area);d.append(include,resolution,node('p','Link this assertion to saved edits:'));for(const change of data.history){const label=node('label',`Edit ${change.event.edit_version} · ${change.event.reason}`),c=node('input','');c.type='checkbox';c.value=change.change_ref;c.className='change-ref';label.append(c);d.append(label);}for(const [decision,text] of [['deferred','Defer'],['rejected','Reject']]){const b=node('button',text);b.addEventListener('click',()=>run(async()=>{await api('/api/intake/disposition',{intake_id:item.intake_id,decision,reviewer:$('reviewer').value,reason:area.value});await load();}));d.append(b);}}else{d.append(node('p',(item.reviewer||'')+' · '+(item.reason||'')));if(item.disposition==='rejected'){const reopen=node('button','Return to pending review');reopen.addEventListener('click',()=>run(async()=>{await api('/api/intake/disposition',{intake_id:item.intake_id,decision:'pending',reviewer:$('reviewer').value,reason:$('reason').value});await load();}));d.append(reopen);}}$('intake').append(d);}}
$('reload').addEventListener('click',()=>run(load));$('intake-form').addEventListener('submit',e=>{e.preventDefault();run(async()=>{await api('/api/intake/stage',{payload:Object.fromEntries(new FormData(e.target))});await load();status('Assertion staged. No catalog fact changed.');});});
$('review').addEventListener('click',()=>run(async()=>{const decisions=[];for(const el of $('intake').children){if(el.querySelector('.include')?.checked)decisions.push({intake_id:el.dataset.intake,resolution:el.querySelector('.resolution').value,change_ids:[...el.querySelectorAll('.change-ref:checked')].map(c=>c.value)});}status('Checking the source baseline and replaying recorded changes…');pending=await api('/api/acceptance/preview',{etag:data.etag,reviewer:$('reviewer').value,reason:$('reason').value,intake_decisions:decisions,previous_token:pending?.token});$('summary').textContent=`${pending.report.history.length} saved edits · ${decisions.length} intake assertions · Reviewer: ${pending.reviewer}. ${pending.reason}`;showHistory($('evidence'),pending.report.history);for(const decision of pending.intake_decisions){const d=node('details','');d.append(node('summary','Intake resolution'));showValue(d,decision);$('evidence').append(d);}$('preview').showModal();status('Source replay passed. Review the acceptance decision.');}));
async function cancel(){if(busy)return;const token=pending?.token;pending=null;$('preview').close();if(token)await run(async()=>{await api('/api/cancel',{token});status('Acceptance cancelled. The draft is unchanged.');});}
$('cancel').addEventListener('click',cancel);$('preview').addEventListener('cancel',e=>{e.preventDefault();cancel();});$('accept').addEventListener('click',()=>run(async()=>{try{await api('/api/acceptance/save',{token:pending.token});await load();status('Accepted. This exact draft can now be validated for a local release.');}finally{pending=null;$('preview').close();}}));
$('release').addEventListener('click',()=>run(async()=>{const result=await api('/api/release/create',{etag:data.etag});$('release-status').textContent='Release validation started. You may keep this page open while it runs.';poll(result.job);}));
async function poll(job){try{const state=await api('/api/release/status?'+new URLSearchParams({job}));$('release-status').textContent=state.state==='failed'?'Release failed: '+state.error:state.state==='completed'?'Release complete and verified.':state.message;if(state.state==='running'){setTimeout(()=>poll(job),2500);return;}if(state.state==='completed'){$('release-result').replaceChildren(node('p',`Release: ${state.release_id}`),node('p',`${state.artifact_count} verified files. Store: ${state.store}`),node('p','Reviewed history and evidence: '+state.evidence),node('p','Publication, backup and restore use the existing local release commands. Production deployment remains separate.'));}}catch(e){$('release-status').textContent=e.message;}}
run(load);
