'use strict';
const $=id=>document.getElementById(id), node=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
const pretty=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const money=n=>n==null?'No separate amount':(n/100).toFixed(2);
let data=null, current=null, queue=[], pending=null, dirty=false, busy=false, snapshot=null, sequence=[], choices={}, loadedModel=null, renderedAction='update';
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function key(row){return Object.fromEntries(data.keys.map(k=>[k,row[k]]));}
function label(row){return [row.rpo,row.name,row.body,row.trim,row.code,row.kind,...data.keys.filter(k=>k!=='revision_id').map(k=>{const ref=data.references[k]?.find(x=>x.value===row[k]);return ref?ref.label:row[k];})].filter(Boolean).join(' · ');}
function filter(){const term=$('search').value.toLowerCase();$('record').replaceChildren(...data.rows.map((r,i)=>({r,i})).filter(x=>label(x.r).toLowerCase().includes(term)).map(x=>new Option(label(x.r),x.i)));render();}
function scalar(name,value,field,onChange){const label=node('label',pretty(name)),wrapper=node('div','');let input;
  if(field?.options||field?.reference){input=node('select','');const opts=[...(field.options?.map(v=>({value:v,label:pretty(v)}))||data.references[field.name]||[])];if(field.reference){for(const q of queue.filter(q=>q.action==='create'&&q.table===field.reference[0])){opts.push({value:q.values.id||q.key.id,label:'Queued: '+q.label});}}if(field.nullable)input.append(new Option('No value',''));if(!field.nullable&&!opts.some(o=>o.value===value))input.append(new Option('Choose a value',''));for(const o of opts)input.append(new Option(o.label,o.value));input.value=value??'';}
  else if(typeof value==='boolean'){input=node('select','');input.append(new Option('Yes','true'),new Option('No','false'));input.value=String(value);}
  else{input=node(typeof value==='string'&&value.length>90?'textarea':'input','');input.value=field?.name.endsWith('_minor')&&value!=null?money(value):value??'';if(field?.integer||typeof value==='number'){input.type='number';input.step=field?.name.endsWith('_minor')?'0.01':'1';}else if(input.tagName==='INPUT')input.type='text';}
  input.setAttribute('aria-label',pretty(name));input.dataset.originalNull=String(value===null);
  input.addEventListener('input',()=>{dirty=true;onChange(input.value===''&&value===null?null:typeof value==='boolean'?input.value==='true':input.value);});label.append(input);wrapper.append(label);return wrapper;}
let values={};
function nested(parent,obj,path=[]){for(const [name,value] of Object.entries(obj)){if(value&&typeof value==='object'){const detail=node('details','');detail.append(node('summary',pretty(name)));nested(detail,value,[...path,name]);parent.append(detail);continue;}const locked=!(data.editable_copy_paths[data.rows.indexOf(current)]||[]).some(p=>JSON.stringify(p)===JSON.stringify([...path,name]));const control=scalar([...path,name].join(' / '),value,null,newValue=>{let target=values.presentation;for(const p of path)target=target[p];target[name]=typeof value==='number'&&newValue!==null?Number(newValue):newValue;});if(locked)control.querySelector('input,select,textarea').disabled=true;parent.append(control);}}
function render(){renderedAction=$('action').value;current=$('action').value==='create'?data?.new_record:data?.rows[Number($('record').value)];$('fields').replaceChildren();values={};if(!current){$('title').textContent=data?.new_record?'Choose Add a new rule or membership to start':'Choose an existing record to edit or copy';return;}$('title').textContent=data.label;for(const field of data.fields){if(field.name==='revision_id')continue;const editable=!field.key||['clone','create'].includes($('action').value);if(field.name==='presentation'){values.presentation=JSON.parse(current.presentation);nested($('fields'),values.presentation);continue;}values[field.name]=current[field.name];const control=scalar(field.name.replace('_minor',' (price)'),current[field.name],field.name==='id'?{...field,reference:null}:field,v=>values[field.name]=v);control.querySelector('input,select,textarea').disabled=!editable||field.name==='id';$('fields').append(control);}dirty=false;}
function collect(){const result={};for(const field of data.fields){if(field.name==='revision_id'||field.name==='id'||field.key&&!['clone','create'].includes($('action').value))continue;let value=values[field.name];if(field.name==='presentation'){value=JSON.stringify(value);}else if(field.integer&&value!==null){if(field.name.endsWith('_minor')&&typeof value==='string'){if(!/^\d{1,9}(\.\d{1,2})?$/.test(value))throw Error('Enter a nonnegative price with at most two decimals');const [whole,fraction='']=value.split('.');value=Number(whole)*100+Number(fraction.padEnd(2,'0'));}else{if(value==='')value=null;else{value=Number(value);if(!Number.isSafeInteger(value))throw Error('Enter a whole number');}}}else if(value===''&&field.nullable)value=null;if(value!==current[field.name]||$('action').value==='create')result[field.name]=value;}return result;}
function queued(){ $('queue-list').replaceChildren(...queue.map((q,i)=>{const d=node('div','');d.append(node('p',`${i+1}. ${pretty(q.action)} · ${q.label}`));const b=node('button','Remove from queue');b.addEventListener('click',()=>{queue.splice(i,1);queued();});d.append(b);return d;}));if(!queue.length)$('queue-list').append(node('p','No changes queued.'));}
async function load(){data=await api('/api/records?'+new URLSearchParams({revision:$('model').value,table:$('family').value}));if(queue.length&&snapshot!==data.etag)throw Error('The draft changed. Clear the queue and reload before reviewing.');snapshot=data.etag;loadedModel=$('model').value;$('evidence').replaceChildren(...data.evidence.map(e=>node('li',`${e.source_path} · ${e.locator} · ${e.content_sha256}`)));$('history').replaceChildren(...data.history.map(h=>node('p',`Edit ${h.edit_version} · ${h.saved_at} · ${h.reason}`)));filter();}
async function loadChoices(){const revision=$('model').value;for(const table of ['configuration','option','interior'])choices[table]=(await api('/api/records?'+new URLSearchParams({revision,table}))).rows;$('configuration').replaceChildren(...choices.configuration.map(c=>new Option(`${c.body} ${c.trim}`,c.id)));targets();}
function targets(){const table=$('build-action').value==='interior'?'interior':'option';$('build-target').replaceChildren(...choices[table].map(r=>new Option([r.rpo,r.name,r.code,r.id].filter(Boolean).join(' · '),r.id)));}
function discard(){return !(dirty||queue.length)||confirm('Discard unsaved and queued changes?');}
$('model').addEventListener('change',()=>run(async()=>{if(!discard()){$('model').value=loadedModel;return;}queue=[];sequence=[];queued();await load();await loadChoices();}));
$('family').addEventListener('change',()=>run(async()=>{if(dirty&&!confirm('Discard unqueued field changes?')){$('family').value=data.table;return;}await load();}));
$('search').addEventListener('input',()=>{if(!dirty||confirm('Discard unqueued field changes?'))filter();});$('record').addEventListener('change',()=>{if(dirty&&!confirm('Discard unqueued field changes?')){$('record').value=data.rows.indexOf(current);return;}render();});$('action').addEventListener('change',()=>{if(!dirty||confirm('Discard unqueued field changes?'))render();else $('action').value=renderedAction;});
$('reload').addEventListener('click',()=>run(async()=>{if(discard()){queue=[];queued();await load();}}));
$('queue').addEventListener('click',()=>run(async()=>{if(!current)throw Error('Choose a record');const change={table:data.table,key:key(current),values:collect(),action:$('action').value,label:label(current)};if(queue.some(q=>q.action!=='clone'&&change.action!=='clone'&&q.table===change.table&&JSON.stringify(q.key)===JSON.stringify(change.key)))throw Error('This record is already queued. Remove it before replacing its change.');queue.push(change);dirty=false;queued();status('Queued. Add related records or review the complete change.');}));
$('clear').addEventListener('click',()=>{queue=[];queued();});$('build-action').addEventListener('change',targets);
$('add-step').addEventListener('click',()=>{sequence.push({action:$('build-action').value,target:$('build-target').value});$('steps').append(node('li',$('build-action').selectedOptions[0].text+' · '+$('build-target').selectedOptions[0].text));});$('clear-steps').addEventListener('click',()=>{sequence=[];$('steps').replaceChildren();});
function differences(parent,before,after,path=''){const keys=new Set([...Object.keys(before||{}),...Object.keys(after||{})]);for(const k of keys){const b=before?.[k],a=after?.[k];if(JSON.stringify(b)===JSON.stringify(a))continue;if(k==='presentation'){differences(parent,JSON.parse(b||'{}'),JSON.parse(a||'{}'),path+'Copy / ');}else if(b&&a&&typeof b==='object'&&typeof a==='object'){differences(parent,b,a,path+pretty(k)+' / ');}else parent.append(node('p',`${path}${pretty(k)}: ${k.endsWith('_minor')?money(b):b??'None'} → ${k.endsWith('_minor')?money(a):a??'None'}`));}}
function projection(parent,state){if(!state){parent.append(node('p','No valid witness found.'));return;}if(state.refused){parent.append(node('p','Refused: '+state.refused));return;}parent.append(node('p',`Total: ${money(state.total_minor)} · Selected: ${state.resolved.map(o=>o.rpo||o.label).join(', ')||'None'}`),node('p','Charges: '+state.charges.map(c=>`${c.label} ${money(c.amount_minor)}`).join('; ')),node('p','Independent purchases: '+state.intent.map(id=>state.resolved.find(o=>o.option_id===id)?.label||id).join(', ')),node('p','Installed equipment: '+state.installed_equipment.map(o=>o.rpo||o.label).join(', ')),node('p','Order codes: '+state.order_codes.map(o=>o.rpo).join(', ')),node('p','Interior: '+(state.selected_interior?.hierarchy.interior_leaf_label||'None')),node('p','Incomplete choices: '+(state.missing_requirements.join('; ')||'None')));for(const cause of state.ownership||[])parent.append(node('p',`Supply: ${state.resolved.find(o=>o.option_id===cause.option_id)?.label||cause.option_id} · ${cause.origin} · ${cause.peer_policy} · owners: ${cause.roots.map(id=>state.resolved.find(o=>o.option_id===id)?.label||id).join(', ')}`));}
$('review').addEventListener('click',()=>run(async()=>{if(dirty)throw Error('Queue the current fields before reviewing.');status('Evaluating the queued changes…');pending=await api('/api/records/preview',{revision_id:$('model').value,etag:snapshot,requests:queue.map(({label,...q})=>q),reason:$('reason').value,scenarios:sequence.length?[{configuration_id:$('configuration').value,actions:sequence}]:[],previous_token:pending?.token});$('diff').replaceChildren();for(const op of pending.operations){const d=node('details','');d.open=true;d.append(node('summary',pretty(op.table)));differences(d,op.before,op.after);$('diff').append(d);}$('outcomes').replaceChildren();for(let i=0;i<pending.after_outcomes.length;i++){const a=pending.after_outcomes[i],b=pending.before_outcomes[i],d=node('details','');d.append(node('summary',a.label),node('h3','Before'));for(const s of b.steps)projection(d,s);d.append(node('h3','After'));for(const s of a.steps)projection(d,s);$('outcomes').append(d);}for(const phase of ['before','after']){const group=node('details','');group.append(node('summary',pretty(phase)+' connected witnesses'));for(const c of pending['connected_'+phase]){const d=node('details','');d.append(node('summary',c.label+' · '+c.configuration_id));projection(d,c.state||{refused:c.refused||c.coverage});group.append(d);}$('outcomes').append(group);}$('preview').showModal();status('Review all recorded changes before saving.');}));
async function cancel(){if(busy)return;const token=pending?.token;pending=null;$('preview').close();if(token)await run(async()=>{await api('/api/cancel',{token});status('Cancelled. Your queued edits remain unsaved.');});}
$('cancel').addEventListener('click',cancel);$('preview').addEventListener('cancel',e=>{e.preventDefault();cancel();});
$('save').addEventListener('click',()=>run(async()=>{try{await api('/api/records/save',{token:pending.token});queue=[];dirty=false;queued();await load();status('Saved as a draft. Review acceptance before creating a release.');}finally{pending=null;$('preview').close();}}));
window.addEventListener('beforeunload',e=>{if(dirty||queue.length){e.preventDefault();e.returnValue='';}});
run(async()=>{const models=await api('/api/catalog'),editors=await api('/api/editors');$('model').replaceChildren(...models.models.map(m=>new Option(m.name,m.revision_id)));$('family').replaceChildren(...editors.editors.map(e=>new Option(e.label,e.table)));await load();await loadChoices();queued();});
